---
name: CI

on:
  push:
    branches:
      - main
      - dev
    tags: '*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight on Sunday every week

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.flavor.os }} - ${{ matrix.flavor.arch }}
    runs-on: ${{ matrix.flavor.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.x'  # Latest version
          # - '1.9'  # Specific stable version
        flavor:
          - {os: ubuntu-latest, arch: x64}  # Linux x64
          - {os: macos-latest, arch: arm64}  # macOS ARM
          - {os: windows-latest, arch: x64}  # Windows x64

    steps:
      - uses: actions/checkout@v4

      # - name: Get number of CPU cores
      #   uses: SimenB/github-actions-cpu-cores@v2
      #   id: cpu-cores

      # - name: Set JULIA_NUM_THREADS
      #   shell: bash
      #   run: >-
      #     echo "JULIA_NUM_THREADS=${{ steps.cpu-cores.outputs.count }}" >> $GITHUB_ENV

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.flavor.arch }}

      - uses: julia-actions/cache@v2
        with:
          cache-registries: "true"

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
        env:
          GKSwstype: 100  # Disable graphics output during tests

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info

  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.x'

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1


      - name: Setup benchmark environment
        run: |
          cd benchmark
          julia --project=. -e 'import Pkg; Pkg.develop(path=".."); Pkg.instantiate()'

      - name: Run benchmarks
        working-directory: benchmark
        run: |
          julia --project=. -e '
            include("discretized_operator_performance_test.jl");
            main(; bench_seconds=1)' | tee results.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ github.sha }}
          path: benchmark/results.txt
          retention-days: 30
